# Generated by Django 3.0.6 on 2022-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0015_auto_20220325_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('belongs_to_collection', models.TextField()),
                ('budget', models.FloatField()),
                ('genres', models.TextField()),
                ('homepage', models.CharField(max_length=400)),
                ('imdb_id', models.CharField(max_length=200)),
                ('original_language', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=200)),
                ('production_companies', models.TextField()),
                ('production_countries', models.TextField()),
                ('release_date', models.CharField(max_length=200)),
                ('revenue', models.FloatField()),
                ('runtime', models.FloatField()),
                ('spoken_languages', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=200)),
                ('video', models.TextField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('imdb_url', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('img_url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie2',
        ),
    ]
